### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by gabebw** [thoughtbot/griddler-sendgrid#10]
This adapter has languished and deserves a new maintainer.

If you're interested, comment here with your qualifications to be the new maintainer.

/cc @sendgrid @theycallmeswift

**Comment by sdhull** [comment]
I can probably help with this some, however I'd be hesitant to over-commit (hah).

I've been a Rails developer since 2009 and have contributed to various open source projects (most recently zurb foundation, however also webmock & rspec many moons ago).

**Comment by gabebw** [comment]
@sdhull Oh jeez, I am so late in replying to you! Are you still interested? If so, I'll make you an admin of this repository.

**Comment by sdhull** [comment]
Sure! Why not

**Comment by wingrunr21** [comment]
@gabebw there probably needs to be someone at least handling issues/PRs for this gem. I don't use SendGrid but if @sdhull is no longer interested I can do it (since I'm already doing that for Griddler). Looks like at the minimum this gem needs a new release cut.

**Comment by gabebw** [comment]
@wingrunr21 @sdhull I've given you both admin access to this repository.

**Comment by wingrunr21** [comment]
@gabebw thanks. need rubygems too.

**Comment by gabebw** [comment]
@wingrunr21 What's your Rubygems email?

**Comment by wingrunr21** [comment]
stafford.brunk at gmail

**Comment by gabebw** [comment]
@wingrunr21 Just added you.
