### ISSUE TITLE
Add Inbound Parse settings to README

### ISSUE THREAD

**Issue by acmeyer** [thoughtbot/griddler-sendgrid#11]
I was having issues setting up griddler with SendGrid, the body text wasn't appearing. After a lot of headache, I figured out what was wrong. When setting up Inbound Parse settings in your dashboard in SendGrid, make sure to uncheck "Spam Check" and "Send Raw" settings for your parser. Spam check stripped out the body content because it thought some emails were spam (I'm sure there is more you could do to set spam filters correctly). Send Raw was, I am guessing, sending the email in a way that griddler couldn't find the body content and therefore generated nothing.

Once I removed both of these settings, everything worked as expected. Hope to save others similar headaches setting up there inbound email parsers.

**Comment by calebthompson** [comment]
Cool, would you like to create a PR to add a bit about this to the README?

**Comment by acmeyer** [comment]
Just added pr #16 for this
