### ISSUE TITLE
Parse email even if bcc is an empty string

### ISSUE THREAD

**Issue by plicjo** [thoughtbot/griddler-sendgrid#13]
My company, Groundswell, ran a bunch of our email tests against the current version of master. We got an error from the JSON parsing of a few emails.

Parsing an empty JSON string `JSON.parse(""`) throws a `JSON::ParserError: A JSON text must at least contain two octets!`

Guarding against empty strings, in addition to nils, on this line: https://github.com/thoughtbot/griddler-sendgrid/blob/master/lib/griddler/sendgrid/adapter.rb#L51 is really important!

A PR fix is at: https://github.com/thoughtbot/griddler-sendgrid/pull/12

**Comment by calebthompson** [comment]
Resolved by #12
