### ISSUE TITLE
How can I test does the reply hits my host url?

### ISSUE THREAD

**Issue by Blackening999** [thoughtbot/griddler-sendgrid#23]
Hello,

I have followed a tutorial and configured everything as it said and I have issues receiving an api call.
How can I check whether my reply comment hit the API url?

**Comment by wingrunr21** [comment]
Your application should see a `POST` to `/email_processor` with the SendGrid data. Are you trying to test this on your local dev machine?

**Comment by Blackening999** [comment]
@wingrunr21 yes. I have used ngrok for that.
Actually, I found the issue. I've tried to set the Inbound parse to parse all email under @my-domain.com , and it worked only with subdomain specified like @parse.my-domain.com

Thanks for your help!
