### ISSUE TITLE
How to skip SPF validation in 'griddler-sendgrid' gem?

### ISSUE THREAD

**Issue by anjain** [thoughtbot/griddler-sendgrid#31]
Hi,
I am using gem 'griddler' with gem 'griddler-sendgrid' in my ruby on rails app for incoming mails.
It is working fine on staging server but getting issue with production server.
There is no issue in my configuration. I have confirmed this with **sendgrid support**. They told me to use only **DKIM validation** and remove **SPF check** from validations.
I have checked both gem for that but didn't find anything relevant to that.
Here is my gem configuration details:
> ruby '2.2.3'
> gem 'rails', '4.1.2'
> gem 'griddler', '1.4.0'
> gem 'griddler-sendgrid', '1.0.0'

Can someone suggest me how can I skip SPF check validation in gem 'griddler-sendgrid'?
Thanks in advance!

**Comment by stefannibrasil** [comment]
Closing this as this library has been deprecated: https://github.com/thoughtbot/griddler-sendgrid/pull/41
